name: Config Parameter Analysis

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 0 * * 0'  # 每周日运行

jobs:
  analyze-config:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        cd scripts
        pip install -r requirements.txt
        
    - name: Run config analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
      run: |
        cd scripts
        python analyze_config_changes.py
        
    - name: Upload analysis results
      uses: actions/upload-artifact@v3
      with:
        name: config-analysis-results
        path: CONFIG_CHANGE_ANALYSIS.json
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add CONFIG_CHANGE_ANALYSIS.json
        git diff --staged --quiet || git commit -m "Update config analysis results"
        git push
